---
language: python
services: docker

env:
  global:
    - ROLE_NAME=ansible_role_ssl_sign_cert
  matrix:
    - MOLECULE_DISTRO=centos7

install:
# Install test dependencies.
  - pip install molecule
  - pip install docker
  - pip install ansible-lint
  - pip install flake8
# - pip install 'molecule<3' docker

script:
# Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
